### ISSUE TITLE
Handling arrays of monky refs does not work on MongoDB.

### ISSUE THREAD

**Issue by akkunchoi** [behrendtio/monky#40]
Hi. I tried to run tests using real MongoDB by the following steps.

- Added mongoose.connect for using MongoDB.
```
mongoose.connect('mongodb://localhost/monky_test');
```
- Removed test/stub.js

Then the test "handles arrays of monky refs correctly" failed. `user.addressInstances` returned empty array. (on a side note, some test cases failed)

While all asynchronous foreach callbacks of handling arrays of monky refs are not completed, but `Monky.create` method calls its callback.

Here is my suggestion.

lib/monky.js at line 269.
```
if (value instanceof Array) {
  // Embedded document / Array handling

  var hasMonkyRef = false;

  var index = 0;
  _each(value, function(sub, eachDone) {
    if (sub instanceof MonkyRef) {
      hasMonkyRef = true;
      handleMonkyRef(sub, eachDone);
    } else if (sub instanceof Object) {
      Object.keys(sub).forEach(function(path) {
        if (sub.hasOwnProperty(path)) {
          sub[path] = sequence(sub[path]);
        }
      });
      eachDone();
    } else {
      value[index++] = sequence(sub);
      eachDone();
    }
  }, function(err) {
    if (!hasMonkyRef) {
      instance[path] = value;
    }
    cb(err);
  });

}
```

By the way, I think unit tests of 'Monky.create' method should not execute on stub but  on real MongoDB.

**Comment by behrendtio** [comment]
Thanks, PR merged and released as `0.6.11`.
