### ISSUE TITLE
Foreign key relationships not working as expected. 

### ISSUE THREAD

**Issue by SeanDunford** [behrendtio/monky#47]
Given the following 3 factories. 

## Organization 
```
module.exports = monky =>
  monky.factory('organizations', {  });
```
## Teams
```
  module.exports = monky =>
  monky.factory('teams', {
    organizationId: monky.ref('organizations', '_id'),
  });
```
## Users
```
module.exports = monky =>
  monky.factory('users', {
    teamId: monky.ref('teams', '_id'),
    organizationId: monky.ref('organizations', '_id'),
  });
```

I would expect that 
`const user = monky.create('users')`

To create an user that belongs to a team that belongs to an organization but the team that gets created creates a new organization. 

Currently i'm using this as a work around 

```
const org = monky.create('organizations'); 
const team = monky.create('teams', {organizationid: organization._id}); 
const user  = monky.create('users', {organizationid: organization._id, teamId: team._id}); 
```

Any suggestions on how to solve this more elegantly?  If not, any suggestions on what changes i could submit to make 

`const user = monky.create('users')`

work as expected?

**Comment by behrendtio** [comment]
Released with `0.7.1`
